### ISSUE TITLE
Can't interact with loaded remote url

### ISSUE THREAD

**Issue by admc** [LearnBoost/tobi#24]
Correct me if I'm wrong, but shouldn't the following work:

var browser = tobi.createBrowser(80, 'http://www.google.com);
browser.click("input[name=btnG"])

or 

browser.get('/', function(res, $){
  browser.click("input[name=btnG"])
});

Both are giving me an uncaught exception.

**Comment by tj** [comment]
Added Google example. Closed by 7234bffd3c297b1a259fab54f408274835a7d525

seems fine to me :)

**Comment by tj** [comment]
dont forget everything is async so you need a callback
