### ISSUE TITLE
Running App in Test Environment

### ISSUE THREAD

**Issue by mhemesath** [LearnBoost/tobi#30]
When creating a browser via an app,

```
var browser = tobi.createBrowser(app);
```

is there a way to specify the test environment to be used to configure the app?  Or  is the environment to run the application inherited from whatever environment was used when tobi was executed to run the tests?

**Comment by kcbanner** [comment]
You could do something like `process.env.NODE_ENV = 'test';` before you create the browser.

**Comment by tj** [comment]
just depends on NODE_ENV, usually I have a Makefile with:

```
test:
  @NODE_ENV=test expresso test/*.test.js
```

etc

**Comment by mhemesath** [comment]
Thanks guys, that's a good idea. I already stole one of your Makefiles to use as a boilerplate of my own to execute my expresso tests  :-). I'll add the env change in there as well.
