### ISSUE TITLE
While POSTing, 'body' parameter does not seem to take effect

### ISSUE THREAD

**Issue by kcbanner** [LearnBoost/tobi#33]
This code:

``` javascript
var doc = {foo: 'test', bar:'foo', a:1, b:2};

browser.post('/foo/', {body: JSON.stringify(doc)}, function(res, $) {
    ...
}
```

produces a req.body of `undefined` in my express view.

**Comment by kcbanner** [comment]
Confirming that a 

``` python
>>> urllib.urlopen('http://localhost:8000/foo/', json.dumps({'a':1}))
```

works, so the issue isn't on the server side.

**Comment by kcbanner** [comment]
Looks like I needed to provide the Content-Type header:

``` javascript
browser.post('/foo/', {body: JSON.stringify(doc),
                   headers: { 'Content-Type':'application/json' } },
                   function(res, $) {
                       ....
                   }
);
```

**Comment by tj** [comment]
I can't remember if we auto-detect/set content-type, would be nice to just have `browser.post('/foo', obj)` if we dont already, been a while haha. if not try setting the Content-Type first so express knows what to do with it
