### ISSUE TITLE
Update jQuery Version

### ISSUE THREAD

**Issue by mhemesath** [LearnBoost/tobi#43]
Is there any reason why jQuery is at version 1.4.2?  The only reason I noticed is I was using a 1.5.x API that wasn't present.

**Comment by tj** [comment]
i think there was actually an issue with jsdom with some versions, feel free to try upgrading and running the tests though, I just haven't had time

**Comment by mhemesath** [comment]
Cool, thx I can take a look. I just wanted to know if there was any back history on this before I jumped into it.
