### ISSUE TITLE
body of 4xx and 5xx errors unavailable 

### ISSUE THREAD

**Issue by psd** [LearnBoost/tobi#56]
tobi only returns the body contents for a "successful" response (where the status is between 200 and 300) which precludes testing the representation returned in a 404 page, 400/422 errors returned for invalid forms input and a 500 error (admittedly hard to recreate normal processing).

**Comment by tj** [comment]
shit yeah that's not good one sec

**Comment by psd** [comment]
there's a pull request to fix this: https://github.com/LearnBoost/tobi/pull/57
