### ISSUE TITLE
Exporting the cookie-jar as its own module

### ISSUE THREAD

**Issue by osher** [LearnBoost/tobi#80]
The cookie and cookie-jar classes looks quite independent and very useful.
I came accross it when I saw that it was coppied 'as is' into mikael's 'request' module, into some ./vendor/ lib in his project.

Instead of copying it also myself - I want to ask:
Have you considered moving them to their own module?
It does not need much, just moving their tests with them with a package.json  and I suppose.

If not, with your permission, may I? In that case, what would satisfy your copyrights?

Thanks, 
Osher

**Comment by tj** [comment]
yeah sure go nuts, I guess just mention that I helped write it, doesn't matter to me but you're right it should be in its own module

**Comment by osher** [comment]
Great - thanks. 
Though by now i saw that finding a name for the package is a mess...
I also found 'tough-cookies'.

I'll hopefully get to it, because i think the simplicity and the elegance justifies.
